# Generated by Django 4.1.7 on 2023-02-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_listing_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='shoeSize',
            new_name='shoe_size',
        ),
    ]
