# Generated by Django 4.1.7 on 2023-02-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_rename_shoesize_listing_shoe_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='shoe',
            new_name='shoe_id',
        ),
    ]
